version: "2"

networks:
  gitea:
    external: false

volumes:
  gitea_postgres:
    driver: local
  postgres:
    driver: local

services:
  server:
    image: gitea/gitea:1.8
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - gitea_postgres:/data
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image:  postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - postgres:/var/lib/postgresql/data
