---
- name: add docker Repo
  yum_repository:
    name: docker-ce
    description: Docker CE repo
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker-ce
  yum:
    name: docker-ce
    state: present

- name: install docker-ce-cli
  yum:
    name: docker-ce-cli
    state: present

- name: install containerd.io
  yum:
    name: containerd.io
    state: present

- name: install Docker compose
  shell: curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: get docker-compose python deps
  shell: pip install docker docker-compose

- name: set PATH
  shell: echo "export PATH=${PATH}:/usr/local/bin" >> /etc/profile

- name: start Docker 
  systemd:
    name: docker
    enabled: yes
    masked: no
    state: started
