---
- name: install vim
  yum:
    name: vim
    state: present

- name: install git
  yum:
    name: git
    state: present

- name: install curl-devel
  yum:
    name: curl-devel
    state: present

- name: install expat-devel
  yum:
    name: expat-devel
    state: present

- name: install gettext-devel
  yum:
    name: gettext-devel
    state: present

- name: install openssl-devel
  yum:
    name: openssl-devel
    state: present

- name: install zlib-devel
  yum:
    name: zlib-devel
    state: present

- name: install make
  yum:
    name: make
    state: present

- name: install pip
  yum:
    name: python-pip
    state: present
